context: dev
configs:
  dev:
    base_url:
    pri_key: <your_pri_key_hex>
    wico_pub_key: <your_wico_public_key_hex>
    encrypt_key: <your_encrypt_key_hex>
    merchant_no:
    channel_id:
    sub_merchant_no:
    # 自然人商户测试挡板信息
    person_mobile: ""
    person_cert_no: ""
    person_username: ""
    person_uid: ""
    person_mybank_account: ""
    person_bank_card_no: ""
